env:
  browser: true
  es6: true
  node: true
plugins: ["node"]
extends: ['eslint:recommended']
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - error
    - never
parserOptions:
  sourceType: "module"
